import express from 'express';
import {
  createReminder,
  getReminders,
  updateReminderStatus,
  getUpcomingReminders
} from '../controllers/reminderController.js';
import protect from '../middleware/authMiddleware.js';

const router = express.Router();

/**
 * POST /api/reminders
 * -------------------
 * Create a reminder manually.
 * Normally reminders are auto-generated by the cron job,
 * but this allows manual creation for testing or custom reminders.
 * Controller: createReminder
 * Middleware: protect (requires authentication)
 */
router.post('/', protect, createReminder);

/**
 * GET /api/reminders
 * ------------------
 * Fetch all reminders for the logged-in patient.
 * Includes pending, sent, and missed reminders.
 * Controller: getReminders
 * Middleware: protect
 */
router.get('/', protect, getReminders);

/**
 * PUT /api/reminders/:id
 * ----------------------
 * Update the status of a reminder.
 * Used by the cron job or admin tools to mark:
 * - pending → sent
 * - pending → missed
 * - sent → (rarely updated)
 * Controller: updateReminderStatus
 * Middleware: protect
 */
router.put('/:id', protect, updateReminderStatus);

/**
 * GET /api/reminders/upcoming
 * ---------------------------
 * Fetch reminders scheduled within the next 24 hours.
 * Used for dashboards, daily summaries, and notifications.
 * Controller: getUpcomingReminders
 * Middleware: protect
 */
router.get('/upcoming', protect, getUpcomingReminders);

export default router;
