import Reminder from '../models/Reminder.js';
import dayjs from 'dayjs';

/* =========================================================
   CREATE REMINDER (Manual)
   ---------------------------------------------------------
   Allows manual creation of reminders.
   Normally reminders are auto-generated by cron jobs,
   but this endpoint is useful for testing or custom reminders.
========================================================= */
export const createReminder = async (req, res) => {
  try {
    const reminder = await Reminder.create({
      ...req.body,       // medication, time, status (optional)
      patient: req.user.id
    });

    res.status(201).json(reminder);
  } catch (error) {
    res.status(500).json({ message: error.message });
  }
};

/* =========================================================
   GET ALL REMINDERS FOR LOGGED-IN PATIENT
   ---------------------------------------------------------
   Returns all reminders (pending, sent, missed)
   belonging to the authenticated patient.
========================================================= */
export const getReminders = async (req, res) => {
  try {
    const reminders = await Reminder.find({ patient: req.user.id });
    res.json(reminders);
  } catch (error) {
    res.status(500).json({ message: error.message });
  }
};

/* =========================================================
   UPDATE REMINDER STATUS
   ---------------------------------------------------------
   Updates a reminder's status (pending → sent → missed).
   SECURITY FIX:
   Ensures the reminder belongs to the logged-in patient.
========================================================= */
export const updateReminderStatus = async (req, res) => {
  try {
    const reminder = await Reminder.findOneAndUpdate(
      { _id: req.params.id, patient: req.user.id }, // ownership check
      { status: req.body.status },
      { new: true }
    );

    if (!reminder) {
      return res.status(404).json({ message: "Reminder not found" });
    }

    res.json({
      message: "Reminder status updated successfully",
      reminder
    });
  } catch (error) {
    res.status(500).json({ message: error.message });
  }
};

/* =========================================================
   UPCOMING REMINDERS (Next 24 Hours)
   ---------------------------------------------------------
   Returns reminders scheduled between NOW and +24 hours.
   Includes medication name + dosage via populate().
========================================================= */
export const getUpcomingReminders = async (req, res) => {
  try {
    const now = dayjs();
    const next24 = now.add(24, 'hour');

    const reminders = await Reminder.find({
      patient: req.user.id,
      time: {
        $gte: now.toDate(),      // now
        $lte: next24.toDate()    // next 24 hours
      }
    })
      .populate('medication', 'name dosage') // include medication info
      .sort({ time: 1 });                    // soonest first

    res.status(200).json({
      count: reminders.length,
      reminders
    });
  } catch (error) {
    res.status(500).json({ message: error.message });
  }
};
